/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mv8_V8Value */

#ifndef _Included_com_mv8_V8Value
#define _Included_com_mv8_V8Value
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mv8_V8Value
 * Method:    _getStringValue
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mv8_V8Value__1getStringValue
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
