/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eclipsesource_v8_V8_MethodDescriptor */

#ifndef _Included_com_eclipsesource_v8_V8_MethodDescriptor
#define _Included_com_eclipsesource_v8_V8_MethodDescriptor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
