/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mv8_V8Isolate */

#ifndef _Included_com_mv8_V8Isolate
#define _Included_com_mv8_V8Isolate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mv8_V8Isolate
 * Method:    _createContext
 * Signature: (JLcom/mv8/V8Context;)J
 */
JNIEXPORT jlong JNICALL Java_com_mv8_V8Isolate__1createContext
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_mv8_V8Isolate
 * Method:    _createObjectTemplate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_mv8_V8Isolate__1createObjectTemplate
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
