/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mv8_V8 */

#ifndef _Included_com_mv8_V8
#define _Included_com_mv8_V8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mv8_V8
 * Method:    _createIsolate
 * Signature: (Lcom/mv8/V8Isolate;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_mv8_V8__1createIsolate
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
