/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mv8_V8ObjectTemplate */

#ifndef _Included_com_mv8_V8ObjectTemplate
#define _Included_com_mv8_V8ObjectTemplate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mv8_V8ObjectTemplate
 * Method:    _registerJavaCallback
 * Signature: (JJLjava/lang/String;Lcom/mv8/JavaCallback;)V
 */
JNIEXPORT void JNICALL Java_com_mv8_V8ObjectTemplate__1registerJavaCallback
  (JNIEnv *, jclass, jlong, jlong, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
