/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mv8_V8Context */

#ifndef _Included_com_mv8_V8Context
#define _Included_com_mv8_V8Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mv8_V8Context
 * Method:    _runScript
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mv8_V8Context__1runScript
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring);

/*
 * Class:     com_mv8_V8Context
 * Method:    _dispose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_mv8_V8Context__1dispose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
